apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mavenwebapprs
  namespace: bhargavi-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  template: # Pod Template
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        image: sivaraasanidocker/maven-web-app:8
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: bhargavi-ns
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
  - port: 80
    targetPort: 8080
